# CARLA-DORA Configuration File

# Network Configuration
network:
  carla_to_dora_port: 8001  # Port for CARLA to send sensor data to DORA
  dora_to_carla_port: 8002  # Port for DORA to send control to CARLA
  host: localhost

# CARLA Configuration
carla:
  host: localhost
  port: 2000
  timeout: 10.0
  
  # Leaderboard settings
  routes: routes/route_01.xml
  scenarios: scenarios/scenario_01.json
  
  # Agent settings
  agent: carla_agent/agent_wrapper.py
  agent_config: config/agent_config.json

# DORA Configuration
dora:
  dataflow: config/carla_dora_dataflow.yml
  
# Sensor Configuration
sensors:
  gps:
    enabled: true
  imu:
    enabled: true
  speedometer:
    enabled: true
    frequency: 20
  camera:
    enabled: true
    width: 800
    height: 600
    fov: 100

# Control Configuration
control:
  pid:
    speed:
      kp: 0.5
      ki: 0.1
      kd: 0.05
    steering:
      kp: 1.0
      ki: 0.0
      kd: 0.1
